version: "3.9"

services: #Services names
  app:
    build:
      context: .
      args: 
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - .:/app #mounting current directory to /app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
      